# basic options   i can say whatever i want here
title: Welcome to Zero's and One's website!
author: L0ngD1nh
email: your-email@domain.com
description: A wonderful site
twitter_username: I have no twitter :(
github_username:  L0ngD1nh

# Build settings
markdown: kramdown
theme: minima
