# basic options, i can say whatever i want here
title: Welcome to Zero's and One's website! -L0ngD1nh
author: L0ngD1nh
email: i27tony29@yahoo.com
description: A wonderful site
twitter_username: I have no twitter
github_username:  L0ngD1nh
instagram_username: Longdinh_
youtube_username: [youtube_username](https://www.youtube.com/channel/UCcsfz_MP7SsERzZmOzEXaDA)

# Build settings
markdown: kramdown
theme: minima
